// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: im_cloud/user/v2/user.proto

package v2

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetUserLoginStatusReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserLoginStatusReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserLoginStatusReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserLoginStatusReqMultiError, or nil if none found.
func (m *GetUserLoginStatusReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserLoginStatusReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserID

	if len(errors) > 0 {
		return GetUserLoginStatusReqMultiError(errors)
	}

	return nil
}

// GetUserLoginStatusReqMultiError is an error wrapping multiple validation
// errors returned by GetUserLoginStatusReq.ValidateAll() if the designated
// constraints aren't met.
type GetUserLoginStatusReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserLoginStatusReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserLoginStatusReqMultiError) AllErrors() []error { return m }

// GetUserLoginStatusReqValidationError is the validation error returned by
// GetUserLoginStatusReq.Validate if the designated constraints aren't met.
type GetUserLoginStatusReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserLoginStatusReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserLoginStatusReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserLoginStatusReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserLoginStatusReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserLoginStatusReqValidationError) ErrorName() string {
	return "GetUserLoginStatusReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserLoginStatusReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserLoginStatusReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserLoginStatusReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserLoginStatusReqValidationError{}

// Validate checks the field values on GetUserLoginStatusReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserLoginStatusReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserLoginStatusReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserLoginStatusReplyMultiError, or nil if none found.
func (m *GetUserLoginStatusReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserLoginStatusReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetUserLoginStatusReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetUserLoginStatusReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetUserLoginStatusReplyValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetUserLoginStatusReplyMultiError(errors)
	}

	return nil
}

// GetUserLoginStatusReplyMultiError is an error wrapping multiple validation
// errors returned by GetUserLoginStatusReply.ValidateAll() if the designated
// constraints aren't met.
type GetUserLoginStatusReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserLoginStatusReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserLoginStatusReplyMultiError) AllErrors() []error { return m }

// GetUserLoginStatusReplyValidationError is the validation error returned by
// GetUserLoginStatusReply.Validate if the designated constraints aren't met.
type GetUserLoginStatusReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserLoginStatusReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserLoginStatusReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserLoginStatusReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserLoginStatusReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserLoginStatusReplyValidationError) ErrorName() string {
	return "GetUserLoginStatusReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserLoginStatusReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserLoginStatusReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserLoginStatusReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserLoginStatusReplyValidationError{}
