// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: common/model/v2/conn.proto

package v2

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分页
type Pagination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	No   int32 `protobuf:"varint,1,opt,name=no,proto3" json:"no,omitempty"`
	Size int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_model_v2_conn_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_common_model_v2_conn_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_common_model_v2_conn_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetNo() int32 {
	if x != nil {
		return x.No
	}
	return 0
}

func (x *Pagination) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Conn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ws的rpc地址
	RpcAddr string `protobuf:"bytes,1,opt,name=rpcAddr,proto3" json:"rpcAddr,omitempty"`
	// 平台 IOS Android Windows OSX Web MiniWeb Linux
	Platform string `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	// 用户id
	UserID string `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	// 用户token
	Token string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	// 链接唯一id
	ConnID       string `protobuf:"bytes,5,opt,name=connID,proto3" json:"connID,omitempty"`
	IsBackground bool   `protobuf:"varint,6,opt,name=isBackground,proto3" json:"isBackground,omitempty"` //是否后台运行
	Language     string `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`          //客户端默认语言
	TenantId     string `protobuf:"bytes,8,opt,name=tenantId,proto3" json:"tenantId,omitempty"`          //用户租户
}

func (x *Conn) Reset() {
	*x = Conn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_model_v2_conn_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Conn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conn) ProtoMessage() {}

func (x *Conn) ProtoReflect() protoreflect.Message {
	mi := &file_common_model_v2_conn_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conn.ProtoReflect.Descriptor instead.
func (*Conn) Descriptor() ([]byte, []int) {
	return file_common_model_v2_conn_proto_rawDescGZIP(), []int{1}
}

func (x *Conn) GetRpcAddr() string {
	if x != nil {
		return x.RpcAddr
	}
	return ""
}

func (x *Conn) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Conn) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *Conn) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Conn) GetConnID() string {
	if x != nil {
		return x.ConnID
	}
	return ""
}

func (x *Conn) GetIsBackground() bool {
	if x != nil {
		return x.IsBackground
	}
	return false
}

func (x *Conn) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Conn) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 设置后台运行
type SetBackgroundStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsBackground bool `protobuf:"varint,1,opt,name=isBackground,proto3" json:"isBackground,omitempty"`
}

func (x *SetBackgroundStatusReq) Reset() {
	*x = SetBackgroundStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_model_v2_conn_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetBackgroundStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBackgroundStatusReq) ProtoMessage() {}

func (x *SetBackgroundStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_model_v2_conn_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBackgroundStatusReq.ProtoReflect.Descriptor instead.
func (*SetBackgroundStatusReq) Descriptor() ([]byte, []int) {
	return file_common_model_v2_conn_proto_rawDescGZIP(), []int{2}
}

func (x *SetBackgroundStatusReq) GetIsBackground() bool {
	if x != nil {
		return x.IsBackground
	}
	return false
}

// 设置客户端语言
type SetLanguageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
}

func (x *SetLanguageReq) Reset() {
	*x = SetLanguageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_model_v2_conn_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLanguageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLanguageReq) ProtoMessage() {}

func (x *SetLanguageReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_model_v2_conn_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLanguageReq.ProtoReflect.Descriptor instead.
func (*SetLanguageReq) Descriptor() ([]byte, []int) {
	return file_common_model_v2_conn_proto_rawDescGZIP(), []int{3}
}

func (x *SetLanguageReq) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// 加密返回
type EncryptionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int32      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`    //网络状态
	Msg    string     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`       //错误信息
	Reason string     `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` //错误原因
	Data   *SingedMsg `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`     //加密数据
}

func (x *EncryptionReply) Reset() {
	*x = EncryptionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_model_v2_conn_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptionReply) ProtoMessage() {}

func (x *EncryptionReply) ProtoReflect() protoreflect.Message {
	mi := &file_common_model_v2_conn_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptionReply.ProtoReflect.Descriptor instead.
func (*EncryptionReply) Descriptor() ([]byte, []int) {
	return file_common_model_v2_conn_proto_rawDescGZIP(), []int{4}
}

func (x *EncryptionReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EncryptionReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *EncryptionReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EncryptionReply) GetData() *SingedMsg {
	if x != nil {
		return x.Data
	}
	return nil
}

// 签名请求参数
type SingedMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 加密数据
	Sign string `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"` // 签名
}

func (x *SingedMsg) Reset() {
	*x = SingedMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_model_v2_conn_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingedMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingedMsg) ProtoMessage() {}

func (x *SingedMsg) ProtoReflect() protoreflect.Message {
	mi := &file_common_model_v2_conn_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingedMsg.ProtoReflect.Descriptor instead.
func (*SingedMsg) Descriptor() ([]byte, []int) {
	return file_common_model_v2_conn_proto_rawDescGZIP(), []int{5}
}

func (x *SingedMsg) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *SingedMsg) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

// 上报数据
type EscalationData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId string     `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"` //节点id
	Data   *SingedMsg `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`     //上报数据
}

func (x *EscalationData) Reset() {
	*x = EscalationData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_model_v2_conn_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EscalationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscalationData) ProtoMessage() {}

func (x *EscalationData) ProtoReflect() protoreflect.Message {
	mi := &file_common_model_v2_conn_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscalationData.ProtoReflect.Descriptor instead.
func (*EscalationData) Descriptor() ([]byte, []int) {
	return file_common_model_v2_conn_proto_rawDescGZIP(), []int{6}
}

func (x *EscalationData) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EscalationData) GetData() *SingedMsg {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_common_model_v2_conn_proto protoreflect.FileDescriptor

var file_common_model_v2_conn_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x76,
	0x32, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76,
	0x32, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x0a, 0x50, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6e, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0xde, 0x01, 0x0a,
	0x04, 0x43, 0x6f, 0x6e, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x70, 0x63, 0x41, 0x64, 0x64, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x70, 0x63, 0x41, 0x64, 0x64, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e,
	0x6e, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x6e, 0x49,
	0x44, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x73, 0x42, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x42, 0x61, 0x63, 0x6b, 0x67,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x3c, 0x0a,
	0x16, 0x53, 0x65, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x73, 0x42, 0x61, 0x63,
	0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69,
	0x73, 0x42, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x35, 0x0a, 0x0e, 0x53,
	0x65, 0x74, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x23, 0x0a,
	0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x22, 0x83, 0x01, 0x0a, 0x0f, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x65, 0x64, 0x4d,
	0x73, 0x67, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x33, 0x0a, 0x09, 0x53, 0x69, 0x6e, 0x67,
	0x65, 0x64, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x22, 0x5c, 0x0a,
	0x0e, 0x45, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x69, 0x6e, 0x67,
	0x65, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x4f, 0x0a, 0x13, 0x61,
	0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x76, 0x32, 0x50, 0x01, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x70, 0x61, 0x72, 0x6b, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x73, 0x70, 0x61, 0x72,
	0x6b, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x76, 0x32, 0x3b, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_model_v2_conn_proto_rawDescOnce sync.Once
	file_common_model_v2_conn_proto_rawDescData = file_common_model_v2_conn_proto_rawDesc
)

func file_common_model_v2_conn_proto_rawDescGZIP() []byte {
	file_common_model_v2_conn_proto_rawDescOnce.Do(func() {
		file_common_model_v2_conn_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_model_v2_conn_proto_rawDescData)
	})
	return file_common_model_v2_conn_proto_rawDescData
}

var file_common_model_v2_conn_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_common_model_v2_conn_proto_goTypes = []interface{}{
	(*Pagination)(nil),             // 0: api.common.model.v2.Pagination
	(*Conn)(nil),                   // 1: api.common.model.v2.Conn
	(*SetBackgroundStatusReq)(nil), // 2: api.common.model.v2.SetBackgroundStatusReq
	(*SetLanguageReq)(nil),         // 3: api.common.model.v2.SetLanguageReq
	(*EncryptionReply)(nil),        // 4: api.common.model.v2.EncryptionReply
	(*SingedMsg)(nil),              // 5: api.common.model.v2.SingedMsg
	(*EscalationData)(nil),         // 6: api.common.model.v2.EscalationData
}
var file_common_model_v2_conn_proto_depIdxs = []int32{
	5, // 0: api.common.model.v2.EncryptionReply.data:type_name -> api.common.model.v2.SingedMsg
	5, // 1: api.common.model.v2.EscalationData.data:type_name -> api.common.model.v2.SingedMsg
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_model_v2_conn_proto_init() }
func file_common_model_v2_conn_proto_init() {
	if File_common_model_v2_conn_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_model_v2_conn_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pagination); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_model_v2_conn_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Conn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_model_v2_conn_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetBackgroundStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_model_v2_conn_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLanguageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_model_v2_conn_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_model_v2_conn_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingedMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_model_v2_conn_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EscalationData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_model_v2_conn_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_model_v2_conn_proto_goTypes,
		DependencyIndexes: file_common_model_v2_conn_proto_depIdxs,
		MessageInfos:      file_common_model_v2_conn_proto_msgTypes,
	}.Build()
	File_common_model_v2_conn_proto = out.File
	file_common_model_v2_conn_proto_rawDesc = nil
	file_common_model_v2_conn_proto_goTypes = nil
	file_common_model_v2_conn_proto_depIdxs = nil
}
