// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v2

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 地址不能为空
func IsAddressNoiEmpty(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorPlatFormNodeReason_ADDRESS_NOI_EMPTY.String() && e.Code == 400
}

// 地址不能为空
func ErrorAddressNoiEmpty(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorPlatFormNodeReason_ADDRESS_NOI_EMPTY.String(), fmt.Sprintf(format, args...))
}

// 地址不能为空
func IsCartePlatformNode(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorPlatFormNodeReason_CARTE_PLATFORM_NODE.String() && e.Code == 500
}

// 地址不能为空
func ErrorCartePlatformNode(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorPlatFormNodeReason_CARTE_PLATFORM_NODE.String(), fmt.Sprintf(format, args...))
}
